"""Add eleven_labs_id to agents

Revision ID: 632348746722
Revises: c12f945a8bad
Create Date: 2025-07-04 23:45:16.678696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '632348746722'
down_revision: Union[str, None] = 'c12f945a8bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('eleven_labs_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'agents', ['eleven_labs_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agents', type_='unique')
    op.drop_column('agents', 'eleven_labs_id')
    # ### end Alembic commands ###
