"""remove unique identidier for eleven_labs_id to agents

Revision ID: f4089fc553a4
Revises: 632348746722
Create Date: 2025-07-05 00:45:58.320650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4089fc553a4'
down_revision: Union[str, None] = '632348746722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agents_eleven_labs_id_key'), 'agents', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('agents_eleven_labs_id_key'), 'agents', ['eleven_labs_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
